# Generated by Django 5.1.5 on 2025-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=2),
        ),
    ]
